---
title: "Gov 50 Final Project"
author: "Pranav Moudgalya"
description: "Government 50 Final Project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in the fields of environmental science, sustainability, and how these fields relate to policy, economics, and markets. By collecting data of investments made by Congress-people over the last two decades, I would like to see how party affiliation may influence the types of companies that politicians invest in, especially with regards to the sustainability of these investments. To gather the relevant data for this project, I would use various data sets such as those offered by OpenSecrets, which is a nonprofit group that tracks money in US politics. I would add to these data sets by collating data from OpenSecrets with online information about how sustainable specific companies are, and by extension, how environmentally responsible the investments of US politicians are. Some factors I would like to study are the party affiliation, length in office, state, and Congress affiliation (Senate vs. House of Reps) of politicians in my dataset.

## Project Proposal
#### Note: Since my initial project thoughts, my idea has changed, reflecting the available data.

As the world progresses towards international cooperation on the climate crisis, the passage of policy to remediate environmental damage and proactively prevent future climate change is an increasingly important instrument in addressing global climate change. Previous research illustrates that one of the most powerful forces in inducing the adoption of climate friendly policies in countries is the adoption of similar policies by other countries (Fankhauser et. al, 2015). However, what domestic factors influence the passage of such policies is understudied. Moreover, whether these policies actually manifest in climate-friendly economic practices is also unclear. Thus, in this research study, we seek to answer two key questions. Firstly, is the per capita fossil fuel energy consumption of a country predictive of the number of policies aimed to promote sustainability and/or mitigate climate change (herein referred to as “climate policies”) that it passes? Secondly, does the passage of climate policies within a country correlate with a positive increase in the amount of renewable energy generated in that country? 

We hypothesis that in countries with higher per capita fossil fuel energy consumption, the quantity of climate policies passed will be lower. We expect that economies who are more heavily reliant on fossil fuels will also have fewer climate policies passed as climate policies usually tend to work against the use of fossil fuels. We also hypothesize that in countries where climate policies are being passed in higher numbers, there will also be increases in the amount of renewable energy consumed in that country. We expect that in countries where climate policies are passed in greater quantity, the ability for renewable energy to be economically competitive with fossil fuel will be higher, and thus be reflected in the amount of renewable energy generated in that country. 

To conduct this research, we will use two datasets. Firstly, to quantify the number of climate policies passed by a country over the past three decades, we will utilize data from the Climate Policy Database. This database houses over 5,000 climate policies passed by 198 countries. To understand how per capita fossil fuel consumption and per capita renewable energy production differ by country, we will utilize the open source data from Our World in Data. To answer our first question, we will conduct a linear regression with per capita fossil fuel energy consumption of a country as our dependent variable, and the quantity of climate change policies in that country as our dependent variable. To answer the second question, we will also conduct a linear regression; the quantity of climate change policies in a country will be the independent variable, and the per capita renewable energy consumption will be the dependent variable. 

If our first regression (namely, that which correlates fossil fuel consumption per capita to climate policies) presents a negative coefficient, it would imply that for every unit increase in fossil fuel consumption, the number of climate policies decreases, and vice versa. Similarly, if our second regression (namely, that which correlates climate policy passage to renewable energy consumption) presents a positive coefficient, it would imply that for every unit increase in the amount of climate policies in a given country, the consumption of renewable energy per capita also increases.

Through this study, we hope to elucidate whether fossil fuel consumption drives the passage of climate policy, and whether the passage of climate policy translates to greater adoption and use of renewable energy. 

